/* generated by tools/build-vfx.py — do not hand-edit.
   Art: Superpowers RPG Battle System pack by Pixel-boy / Sparklin Labs (CC0). */
window.VFX_ATLAS = {
 "cell": 96,
 "cols": 6,
 "rows": 15,
 "effects": {
  "sparkring": {
   "row": 0,
   "frames": 6
  },
  "bolt": {
   "row": 1,
   "frames": 5
  },
  "claw": {
   "row": 2,
   "frames": 5
  },
  "crescent": {
   "row": 3,
   "frames": 5
  },
  "arc": {
   "row": 4,
   "frames": 5
  },
  "cross": {
   "row": 5,
   "frames": 5
  },
  "heal": {
   "row": 6,
   "frames": 6
  },
  "rubble": {
   "row": 7,
   "frames": 6
  },
  "ground": {
   "row": 8,
   "frames": 5
  },
  "fireball": {
   "row": 9,
   "frames": 3
  },
  "scratch": {
   "row": 10,
   "frames": 4
  },
  "flame": {
   "row": 11,
   "frames": 4
  },
  "holy": {
   "row": 12,
   "frames": 6
  },
  "dust": {
   "row": 13,
   "frames": 5
  },
  "swirl": {
   "row": 14,
   "frames": 5
  }
 }
};
