#!/usr/bin/env python3
"""Embed the webfonts as data URIs in css/font.css.

Two variable faces, one axis each, no static weights:

  Plus Jakarta Sans  UI and body text. Humanist-geometric with real
                     personality (flagged 1, double-storey g, open apertures)
                     and a 745/1000 cap height, so it holds at 12-13px.
  Gabarito           Display: headings, HUD counters, hero. Warm, slightly
                     narrow and energetic, which is what keeps the app from
                     reading as default-Inter-everywhere.

Both expose real `tnum`, which matters in an idle game: the previous display
face (Nunito) has no tabular feature at all, so every
`font-variant-numeric: tabular-nums` rule on a counter was a no-op that only
looked right by accident.

Files come from the npm registry (the only font source reachable under this
workspace's network policy) and are cached in assets/fonts/ so a checkout with
no egress still builds.
"""
import base64
import io
import os
import tarfile
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'assets', 'fonts')
VERSION = '5.3.0'

#     css family,  npm package,                 file inside the tarball,      axis
FACES = [
    ('Jakarta',  'plus-jakarta-sans', 'plus-jakarta-sans-latin-wght-normal.woff2', '200 800'),
    ('Gabarito', 'gabarito',          'gabarito-latin-wght-normal.woff2',          '400 900'),
]


def fetch(pkg, fname):
    """Cached fetch of one woff2 out of an @fontsource-variable tarball."""
    local = os.path.join(SRC, fname)
    if os.path.exists(local):
        return open(local, 'rb').read()
    url = (f'https://registry.npmjs.org/@fontsource-variable/{pkg}/-/'
           f'{pkg}-{VERSION}.tgz')
    print(f'  fetching {pkg}@{VERSION}')
    blob = urllib.request.urlopen(url, timeout=60).read()
    with tarfile.open(fileobj=io.BytesIO(blob), mode='r:gz') as tf:
        member = next(m for m in tf.getmembers() if m.name.endswith('/' + fname))
        raw = tf.extractfile(member).read()
    os.makedirs(SRC, exist_ok=True)
    open(local, 'wb').write(raw)
    return raw


def main():
    out = ['/* generated by tools/embed-fonts.py — do not hand-edit.',
           '   Plus Jakarta Sans & Gabarito, SIL Open Font License 1.1.',
           '   See assets/fonts/CREDITS.md. */']
    total = 0
    for family, pkg, fname, axis in FACES:
        raw = fetch(pkg, fname)
        total += len(raw)
        b64 = base64.b64encode(raw).decode()
        # one variable file serves the whole weight range
        out.append(
            f"@font-face{{font-family:'{family}';font-style:normal;"
            f"font-weight:{axis};font-display:block;"
            f"src:url(data:font/woff2;base64,{b64}) format('woff2-variations');}}")
    css = '\n'.join(out) + '\n'
    open(os.path.join(ROOT, 'css', 'font.css'), 'w').write(css)
    print(f'{len(FACES)} variable faces embedded, {total/1000:.0f}KB raw, '
          f'{len(css)/1000:.0f}KB css')


if __name__ == '__main__':
    main()
