#!/usr/bin/env python3
"""Embed the real webfonts as data URIs in css/font.css.

The pixel bitmap font is gone: it was the single biggest reason the UI read as
low-quality at phone sizes. Inter carries UI and body text, Nunito the display
numbers and headings — both fetched from the npm registry (see
assets/fonts/CREDITS.md), the only font source reachable under this workspace's
network policy.
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'assets', 'fonts')

FACES = [
    ('Inter',  'inter-latin-400-normal.woff2',  400),
    ('Inter',  'inter-latin-500-normal.woff2',  500),
    ('Inter',  'inter-latin-600-normal.woff2',  600),
    ('Inter',  'inter-latin-700-normal.woff2',  700),
    ('Nunito', 'nunito-latin-700-normal.woff2', 700),
    ('Nunito', 'nunito-latin-800-normal.woff2', 800),
]


def main():
    out = ['/* generated by tools/embed-fonts.py — do not hand-edit.',
           '   Inter & Nunito, SIL Open Font License 1.1. See assets/fonts/CREDITS.md. */']
    total = 0
    for family, fname, weight in FACES:
        p = os.path.join(SRC, fname)
        raw = open(p, 'rb').read()
        total += len(raw)
        b64 = base64.b64encode(raw).decode()
        out.append(
            f"@font-face{{font-family:'{family}';font-style:normal;font-weight:{weight};"
            f"font-display:block;src:url(data:font/woff2;base64,{b64}) format('woff2');}}")
    open(os.path.join(ROOT, 'css', 'font.css'), 'w').write('\n'.join(out) + '\n')
    print(f'{len(FACES)} faces embedded, {total/1000:.0f}KB raw')


if __name__ == '__main__':
    main()
